# Generated by Django 2.1.4 on 2018-12-29 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='description',
            new_name='descript',
        ),
    ]
